export const PORUDZBENICA_LIST_REQUEST = 'PORUDZBENICA_LIST_REQUEST'
export const PORUDZBENICA_LIST_SUCCESS = 'PORUDZBENICA_LIST_SUCCESS'
export const PORUDZBENICA_LIST_FAIL = 'PORUDZBENICA_LIST_FAIL'